### PR TITLE
feat: upgrade to latest Google Cloud Storage library

### LINKED ISSUE #39: Upgrade GCS library
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-gcs-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server-gcs-adapter/issues?q=is%3Aissue).

### Issue Description

Current version of @google-cloud/storage is 1.7.0 in the lock file, which is an outdated version from 4 years ago, which is a bit concerning. Latest version is 6.2.3.
We found out about this the hard way, as adding gcs-adapter downgraded google-auth-library and broke typescript compilation.

### Expected Outcome

Can we bring the library up to date?

### PR DESCRIPTION
**Pull request by Moumouls**

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by mtrezza** [comment]
@Moumouls There are relatively few changes in this PR, considering that `@google-cloud/storage` jumps from 1.x to 6.x. And we don't have integration tests in this adapter. Did you verify the adapter works with this change?

**Comment by mtrezza** [comment]
@lebenitza could you try out this PR and let us know whether it works?

**Comment by lebenitza** [comment]
@Moumouls thank you for the PR!

@mtrezza I will try to find some time to test this. I will test it on GKE, I want to make sure [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) works and see how it behaves with directAccess on and off.

**Comment by Moumouls** [comment]
Hi @lebenitza 
I'll also test it the week, I'll try it with direct access false and workload identity from a Cloud Run parse Server container

**Comment by Moumouls** [comment]
@mtrezza  @lebenitza I can confirm that everything works correctly. I succeed to upload some files on via Google Cloud Run to GCS.

I can also confirm that workload identity works correctly when directAccess is off. All files are private on GCS.

We are good to go here

**Comment by mtrezza** [comment]
Great, just to confirm, can we merge and release this as a feature version (1.2.0) because despite the GCS upgrade from 1.x to 6.x there is no breaking change for Parse Server?

**Comment by Moumouls** [comment]
No breaking changes @mtrezza  google has not changed interfaces/features used by the GCS adapter. 1.2 is okay

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [1.2.0](https://github.com/parse-community/parse-server-gcs-adapter/releases/tag/1.2.0)

**Pull request merged**
